### ISSUE TITLE
Why not standard console utility?

### ISSUE THREAD

**Issue by lazna** [Killeroo/PowerPing#112]
Why PowerPing when started from console open another window and after press a key it close with all outputs? Standard console utilities run in same console window from where its started and leave output there after its termination.

**Comment by Killeroo** [comment]
It's because PowerPing requires administrative rights (https://github.com/Killeroo/PowerPing/issues/110) so when it starts it tries to run a new console running as an administrator. If the console you are running PowerPing from is already running as an administrator then no new console will open. 

If you want to stop being asked for user input add the ```--noinput``` flag when running PowerPing. In the next release, I have changed this to be a setting that will persist so you will not need to keep specifying it when you run PowerPing (https://github.com/Killeroo/PowerPing/commit/615f78e441a9c5f523f68a34aac60b69e004b75b). It was initially added so that the new console window wouldn't close too quickly.

**Comment by Killeroo** [comment]
I am going to close this ticket as I don't feel there is much else I can really add to it that I haven't already said

**Comment by lazna** [comment]
Understand, but you may take a look how to elevate current console window

https://github.com/gerardog/gsudo/blob/master/internals.md

**Comment by Killeroo** [comment]
This is really interesting, thanks for the link. I will look into this.
