### ISSUE TITLE
Change back ASCII design.

### ISSUE THREAD

**Issue by WNDNCG** [Killeroo/PowerPing#113]
or i just didn't put the correct syntax?

![req](https://user-images.githubusercontent.com/49801838/70840890-ba4c4900-1e50-11ea-8f52-26d20ed3cf07.png)

**Comment by Killeroo** [comment]
Yeah I have been messing around with some alternate ascii characters for the symbols command. As of this commit (https://github.com/Killeroo/PowerPing/commit/f6fd018a7c164e191e4a9e1559a34776f367c1e5) I have switched it back to the way to the way it looks in your example above with block characters so that will mostly likely be the way it looks in the upcoming release. I think it looks better like that, let me know what you think.

**Comment by WNDNCG** [comment]
I like the old one the (. for success ping and ! for down ping), it's more like cisco-ish theme :D.

**Comment by Killeroo** [comment]
Yeah I like that idea, could keep the ```-sym``` argument but an argument after (say the number 1 or 2) to select the theme?

**Comment by Killeroo** [comment]
You can access the original theme using the --sym command and the alternate theme can be accessed by adding 1 (--sym 1) in the most recent release (https://github.com/Killeroo/PowerPing/releases/tag/v1.3.1). I am going to close the ticket for now but please do comment if you have any other suggestions.

**Comment by WNDNCG** [comment]
no suggestion just great program after all this years! cheers!
